---
fixtures:
  repositories:
    apt:
      ref: "2.2.2"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    concat:
      ref: "2.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
    icinga2:
      ref: "v1.0.2"
      repo: "https://github.com/Icinga/puppet-icinga2.git"
    mysql:
      ref: "3.8.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
    puppetdbquery:
      ref: "2.1.1"
      repo: "https://github.com/dalen/puppet-puppetdbquery"
    stdlib:
      ref: "4.12.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    vision_monitoring:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-monitoring"
    vision_puppet:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-puppet"
    vision_groups:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-groups"
    vision_mysql:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-mysql"
  symlinks:
    vision_icinga2: '#{source_dir}'
