---
fixtures:
  repositories:
    apt:
      ref: "2.2.2"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    stdlib:
      ref: "4.12.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    icinga2:
      ref: "556db546d6137b077be36141f8c463b6990aaef5"
      repo: "https://github.com/Icinga/puppet-icinga2"
    vision_monitoring:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-monitoring"
    puppetdbquery:
      ref: "2.1.1"
      repo: "https://github.com/dalen/puppet-puppetdbquery"
    vision_puppet:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-puppet"
    vision_groups:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-groups"
    vision_mysql:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-mysql"
    mysql:
      ref: "3.8.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
  symlinks:
    vision_icinga2: '#{source_dir}'
